### ISSUE TITLE
Goodreads initial feedback

### ISSUE THREAD

**Issue by carissamelanson** [michaelbrownsf/tiy_assignments#7]
Like Casie mentioned this morning, consistency with the Goodreads header on the small format.
Watch out for spacing. On your large formats, you have a nice amount of white space to the left of your content but not an equal amount to the right. For example on the profile page, the beige recommendation box doesn't have any spacing to the right.

**Comment by michaelbrownsf** [comment]
Thanks for your suggestions. I've incorporated them and agree that they were needed changes.
