### ISSUE TITLE
Goodreads Initial Feedback

### ISSUE THREAD

**Issue by abbylarner** [michaelbrownsf/tiy_assignments#9]
Layout:
- Overall, you need more consistency in your spacing between elements and text
- In the navigation, is the sub-navigation dependent on the highlighted navigation element?  If so, you may want to make that bar the same light blue, so those similar elements relate better to each other
- I don't feel like I have a good sense of the homepage because there isn't enough information showing, show different types of updates
- Why is the "want to read" button aligned right when everything else is aligned left?  Can you use that space for something else?
- The spacing on the left edge and right edge of the homepage are drastically different.  Consider setting up a grid to make your spacing more consistent
- Be more consistent with your placement of text.  Right now my eye is moving all over the place (for example profile information and the info below your profile image). How can you layout the text so it is a more natural transition for my eye?
- Be consistent with your capitalization.  Everything is capitalized on your profile page except for "details" and "activity"
- Be consistent with the alignment of your dividing lines
- How will your bookshelf mobile layout change for 50 shelves that each have 250 books? Does the carousel make sense for a user that has a ton of books?

Design:
- Why is your footer color different?  Does that color show up anywhere else on the site? I think you could just  use the same tan color you are using elsewhere in the footer, or possibly the same blue as the navigation to have a similar start and finish to the site
- What does it look like if the book doesn't have a 5-star rating?
- You don't need a different color for each tab on the profile page - make similar elements look similar so the user knows they have similar functionality
- The arrows on your carousels are distracting because they are in front of the books and are also very prominent, consider reducing opacity on them to make the books the main focus

**Comment by michaelbrownsf** [comment]
Abby,

Thanks for your feedback! I've tried several of your suggestions and have incorporated them into the design.

Michael
